### ISSUE TITLE
qemuarm64 does not boot if built with fitimage

### ISSUE THREAD

**Issue by MingliuYan** [torizon/meta-toradex-torizon#18]
qemuarm64 does not boot with the following enabled in conf/auto.conf:

```
KERNEL_CLASSES:append = " kernel-fitimage"
KERNEL_IMAGETYPE:forcevariable = "fitImage"
```

**Comment by leograba** [comment]
cc @sergioprado @rborn-tx just to make you guys aware of this, because as far as I know, we only use FIT image for signed (Secure Boot) images.

**Comment by sergioprado** [comment]
Yeah, Torizon OS doesn't use (and support) FIT images. We currently only use (and support) FIT images on signed images.

Also, `qemuarm64` is not an official supported target for the secure boot feature.

So this is more of a feature request (FIT image support in Torizon OS), than a bug report.

I would be glad to work on official secure boot support for qemuarm64, if this is added to our backlog.

**Comment by MingliuYan** [comment]
@sergioprado Thanks for the input!

I was checking fitimage boot for torizon images and found fitimage boot without problems for toradex modules, because the "kernel_image_type=fitImage" case is being checked in https://github.com/torizon/meta-toradex-torizon/blob/kirkstone-6.x.y/recipes-bsp/u-boot/u-boot-distro-boot/uEnv.txt.in#L46

but the same logic is missing in https://github.com/torizon/meta-toradex-torizon/blob/kirkstone-6.x.y/recipes-bsp/u-boot/u-boot-distro-boot/qemuarm64/uEnv.txt.in, so I created this issue.

it could be fixed by applying the same logic from toradex's uEnv.txt.in, I have made a PR for that: https://github.com/torizon/meta-toradex-torizon/pull/21, maybe we go with that? Or shall I turn this to be a feature requirement?

**Comment by sergioprado** [comment]
Hi @MingliuYan!

Looks good to me. Yeah, since it is a simple fix, and you already have it done, I don't see why we would need to handle it as a feature request.

Anyway, I am not the maintainer of this layer anymore, so the decision is on the current maintainers. :-)
